### ISSUE TITLE
What is a .tff file?

### ISSUE THREAD

**Issue by TLiley2** [incubated-geek-cc/pdf-font-extractor#1]
Why does the pdf-font-extractor extract these made up invalid font file format called .tff instead of extracting a valid font format like .ttf?

**Comment by incubated-geek-cc** [comment]
Hi there! Many thanks for pointing this out. Apologies had made a mistake in the notation of its file extension. The TrueTypeFont extensions are ".ttf" as you have said. Have updated both the application and source code to reflect this error!
